# Generated by Django 3.1.12 on 2023-03-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20200214_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='sh_overview',
            field=models.TextField(default='Sample text of short overview of the course'),
            preserve_default=False,
        ),
    ]
