# Generated by Django 3.1.12 on 2023-03-19 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_delete_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0007_course_sh_overview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('forms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='index.form')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
