# Generated by Django 3.1.12 on 2023-03-02 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_remove_form_see_response'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
