# Generated by Django 3.1.12 on 2023-03-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='next',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
