# Generated by Django 3.1.12 on 2023-03-19 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_form_next'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='next',
        ),
    ]
